version: '3.1'

services:

  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: jiabbrqo
      POSTGRES_PASSWORD: RjqU_23TUceT4cMymkDcT6iF8NgM91UI

  back:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
      dockerfile: Backend/tis4/Dockerfile
    container_name: back
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://silly.db.elephantsql.com:5432/jiabbrqo
      - SPRING_DATASOURCE_USERNAME=jiabbrqo
      - SPRING_DATASOURCE_PASSWORD=RjqU_23TUceT4cMymkDcT6iF8NgM91UI
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  front:
    build:
      context: .
      dockerfile: edn-representacoes/Dockerfile
    command: sh -c "npm run dev -- --host"
    container_name: front
    ports:
      - "5173:5173"